Task: null
TrainingFraction: null
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
all_joints_names:
- snout
- left-ear
- right-ear
- left-front-paw
- right-front-paw
- left-back-paw
- right-back-paw
- tailbase
- tailtip
alphavalue: null
batch_size: 1
bodyparts: null
bottomheight: 400
colormap: null
corner2move2: null
crop: true
cropping: null
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_mouse_homecageMay28/mouse_homecage_Andre95shuffle1.mat
dataset_type: default
date: null
display_iters: 1000
dotsize: null
global_scale: 0.8
init_weights: /home/andre/miniconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
iteration: null
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_mouse_homecageMay28/Documentation_data-mouse_homecage_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
move2corner: null
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 9
numframes2pick: null
pcutoff: null
pos_dist_thresh: 17
project_path: /home/andre/repositories/sussex_neuro/rodent-tracking/test_data/videos/DLC/mouse_homecage-Andre-2020-05-28
resnet: null
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
scorer: null
skeleton: []
skeleton_color: black
snapshotindex: null
start: null
stop: null
topheight: 400
video_sets: null
x1: null
x2: null
y1: null
y2: null
